<?php

namespace ContainerTR2NENx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProgrammationControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ProgrammationController' shared autowired service.
     *
     * @return \App\Controller\ProgrammationController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ProgrammationController'] = $instance = new \App\Controller\ProgrammationController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\ProgrammationController', $container));

        return $instance;
    }
}
