<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerItAiUzW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerItAiUzW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerItAiUzW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerItAiUzW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerItAiUzW\App_KernelDevDebugContainer([
    'container.build_hash' => 'ItAiUzW',
    'container.build_id' => '4c588e16',
    'container.build_time' => 1669710208,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerItAiUzW');
