<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB3CVHHp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB3CVHHp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB3CVHHp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB3CVHHp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB3CVHHp\App_KernelDevDebugContainer([
    'container.build_hash' => 'B3CVHHp',
    'container.build_id' => 'f633b4cc',
    'container.build_time' => 1670067013,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB3CVHHp');
