<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEizROYt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEizROYt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEizROYt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEizROYt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEizROYt\App_KernelDevDebugContainer([
    'container.build_hash' => 'EizROYt',
    'container.build_id' => 'abc067d2',
    'container.build_time' => 1669632339,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEizROYt');
